### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by BazzalSeed** [erikjansson/atom-tab-title#8] opened 2017-08-13 18:55 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tab-title](https://github.com/erikjansson/atom-tab-title) package 0.3.4

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/seedofwind/.atom/packages/tab-title/lib/tab-title.js:78

TypeError: Cannot read property '0' of undefined
    at Object.generateTitle (/packages/tab-title/lib/tab-title.js:78:33)
    at items.forEach (/packages/tab-title/lib/tab-title.js:89:30)
    at Array.forEach (native)
    at Object.setTitle (/packages/tab-title/lib/tab-title.js:85:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:913:33)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:294:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:252:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:54:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app/src/notification.js:79:33)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:256:31)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:145:32)
```

### Commands

```
     -0:06.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-backbone 0.6.1 
atom-beautify 0.30.3 
atom-csscomb 2.0.4 
atom-live-server 2.1.2 
atom-ternjs 0.18.3 
auto-complete-wx 0.9.6 
autoclose-html 0.23.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
autoprefixer 3.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.8 
fold-functions 0.5.0 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.2 
language-generic-config 1.3.0 
language-terraform 0.8.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-ui-default 1.6.2 
MagicPython 1.0.10 
markdown-preview-plus 2.4.10 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
multi-cursor 2.1.5 
pigments 0.39.1 
python-indent 1.1.0 
python-isort 0.0.7 
python-tools 0.6.9 
ssh-config 0.10.1 
tab-title 0.3.4 
tablr 1.8.3 
turbo-javascript 1.4.0 
```

**Comment by erikjansson** [comment] 2017-08-18 06:41
Duplicate of #5. Fixed in today's update!

**Closed as completed by erikjansson** 2017-08-18 06:41 UTC
Labels: duplicate
