### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Sirfrummel** [erikjansson/atom-tab-title#7] opened 2017-08-10 16:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [tab-title](https://github.com/erikjansson/atom-tab-title) package 0.3.4

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/david/.atom/packages/tab-title/lib/tab-title.js:78

TypeError: Cannot read property '0' of undefined
    at Object.generateTitle (/packages/tab-title/lib/tab-title.js:78:33)
    at items.forEach (/packages/tab-title/lib/tab-title.js:89:30)
    at Array.forEach (native)
    at Object.setTitle (/packages/tab-title/lib/tab-title.js:85:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:913:33)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:704:39)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:18.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-no-tab-close-button 1.0.0 
autoclose-html 0.23.0 
black-and-white-ui 0.1.15 
blame 0.12.0 
brilliance-white-theme 1.0.0 
compare-files 0.8.1 
copy-path 0.4.2 
custom-title 1.0.1 
file-icons 2.1.10 
focus-white 0.2.0 
genesis-ui 0.5.0 
git-blame 1.2.1 
git-history 3.3.0 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
hey-pane 1.0.0 
highlight-bad-chars 1.0.7 
material 2.2.0 
material-syntax 0.6.1 
material-ui 1.0.10 
merge-conflicts 1.4.5 
rainbow-windows 0.3.0 
ruby-block 0.3.6 
single-click-open 0.2.2 
solarized-light-ui 0.1.0 
sort-lines 0.14.0 
spacegray-light-neue-ui 0.1.7 
sync-settings 0.8.2 
tab-close 2.1.0 
tab-title 0.3.4 
tree-view-git-status 1.4.0 
white-ui 2.6.2 
```

**Comment by erikjansson** [comment] 2017-08-18 06:41
Duplicate of #5. Fixed in today's update!

**Closed as completed by erikjansson** 2017-08-18 06:41 UTC
Labels: duplicate
